name: pr-test-build-windows

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-test-build-windows:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
        cache-dependency-path: src/go.sum

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Run tests
      run: |
        cd src
        go test -v -timeout 15m ./...

    - name: Build GUI
      run: |
        cd src
        go build -v -ldflags="-s -w -H=windowsgui -extldflags=-static" -o 1.exe ./cmd/picocrypt
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Build CLI-only (no graphics dependencies)
      run: |
        cd src
        go build -v -tags cli -ldflags="-s -w -extldflags=-static" -o Picocrypt-NG-cli.exe ./cmd/picocrypt
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Add icon, manifest, and version info
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile reshacker_setup.zip https://github.com/user-attachments/files/18878075/reshacker_setup.zip
        Expand-Archive -DestinationPath reshacker_setup reshacker_setup.zip
        reshacker_setup/reshacker_setup.exe /SILENT
        Start-Sleep -Seconds 60
        Invoke-Expression "& `"$Env:P`" -open src/1.exe -save src/2.exe -action addoverwrite -res images/key.ico -mask `"ICONGROUP,MAINICON,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/2.exe -save src/3.exe -action addoverwrite -res images/key.ico -mask `"ICONGROUP,A,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/3.exe -save src/4.exe -action addoverwrite -res dist/windows/manifest.xml -mask `"MANIFEST,1,`""
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open dist/windows/versioninfo.rc -save resources.res -action compile"
        Start-Sleep -Seconds 30
        Invoke-Expression "& `"$Env:P`" -open src/4.exe -save src/5.exe -action addoverwrite -res resources.res"
        Start-Sleep -Seconds 30
      env:
        P: "C:\\Program Files (x86)\\Resource Hacker\\ResourceHacker.exe"

    - name: Compress with upx
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile upx.zip https://github.com/upx/upx/releases/download/v5.1.0/upx-5.1.0-win64.zip
        Expand-Archive -DestinationPath upx upx.zip
        upx/upx-5.1.0-win64/upx.exe --lzma -o src/Picocrypt-NG.exe src/5.exe
        upx/upx-5.1.0-win64/upx.exe --lzma src/Picocrypt-NG-cli.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: pr-test-build-windows-ONLY-FOR-TESTING
        path: |
          src/Picocrypt-NG.exe
          src/Picocrypt-NG-cli.exe
        if-no-files-found: error
        compression-level: 9
